#!/bin/sh

set -euf

cp -a tests "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

for python in $(py3versions -s); do
	echo "== $python =="
	$python -m pytest -p pytester \
	    --cov=/usr/lib/python3/dist-packages/pytest_mpi \
	    --runpytest=subprocess \
	    tests/
done
